{% set name = "copc-lib" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RockRobotic/copc-lib/archive/v{{ version }}.tar.gz
  sha256: 2c0f52d0551e063480692cad0fc94637e8685d339f6d6187be146e3e0552c0e8

build:
  number: 1
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - make
    - cmake >=3.18
  host:
    - python
    - pip
    - pybind11 >=2.6.0
    - scikit-build
    - laz-perf =3.0.0
  run:
    - python
    - laz-perf =3.0.0

test:
  imports:
    - copclib
  source_files:
    - cmake/*.cmake
    - test/CMakeLists.txt
    - test/*.cpp
    - test/*.py
    - test/data/*.h
    - example/CMakeLists.txt
    - example/*.cpp
    - example/*.py
  requires:
    - pytest
    - Catch2
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.18

about:
  home: https://github.com/RockRobotics/copc-lib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: copc-lib provides an easy-to-use interface for reading and creating Cloud Optimized Point Clouds

extra:
  recipe-maintainers:
    - CCInc
    - leo-stan
    - arknoll
