{% set name = "copc-lib" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RockRobotic/copc-lib/archive/v{{ version }}.tar.gz
  sha256: b4f5897210f5756e0fbdc807f7d3cefaaa0bed950b1bbb2a3dcbeb3c980dda7d

build:
  number: 1
  skip: true  # [py<36 or (win and py>39)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - make
    - cmake >=3.18
  host:
    - python
    - pip
    - pybind11 >=2.6.0
    - scikit-build
    - laz-perf =3.0.0
    - mypy
  run:
    - python
    - laz-perf =3.0.0
    - numpy

test:
  imports:
    - copclib
  source_files:
    - cmake/*.cmake
    - test/CMakeLists.txt
    - test/*.cpp
    - test/*.py
    - test/data/*.h
    - example/CMakeLists.txt
    - example/*.cpp
    - example/*.py
  requires:
    - pytest
    - Catch2<3
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.18

about:
  home: https://github.com/RockRobotics/copc-lib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: copc-lib provides an easy-to-use interface for reading and creating Cloud Optimized Point Clouds

extra:
  recipe-maintainers:
    - CCInc
    - leo-stan
    - arknoll
